### ISSUE TITLE
Error: classes2.dex is not an apk, dex file or odex file

### ISSUE THREAD

**Issue by RichardHoOoOo** [JordanSamhi/Tools#4]
Hi, If I run ic3.jar with the attached apk, I got this error
```
Exception in thread "main" org.jf.util.ExceptionWithContext: /var/folders/gz/yrhp403121d88lng2j0977yh0000gn/T/classes2.dex is not an apk, dex file or odex file.
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:123)
	at edu.psu.cse.siis.coal.Analysis.computeAnalysisClassesInApk(Analysis.java:305)
	at edu.psu.cse.siis.coal.Analysis.computeAnalysisClasses(Analysis.java:237)
	at edu.psu.cse.siis.ic3.Ic3Analysis.setApplicationClasses(Ic3Analysis.java:230)
	at edu.psu.cse.siis.ic3.Ic3Analysis.setApplicationClasses(Ic3Analysis.java:64)
	at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:71)
	at edu.psu.cse.siis.ic3.Main.main(Main.java:13)

```
Could you help me found the issue?

The apk under test
[app-debug.apk.zip](https://github.com/JordanSamhi/Tools/files/8748983/app-debug.apk.zip)

**Comment by JordanSamhi** [comment]
Hi @RichardHoOoOo,

Seems like a dexlib problem: https://github.com/JesusFreke/smali/tree/master/dexlib2

**Comment by tyousyuka** [comment]
Hello，@JordanSamhi 
I encountered the same problem, 
Is this reason due to multiple dex?
How can I use ic3.jar with multipe-dex? what options need I set?


There is another question，this apk can not generate iccmodel file successful 
(https://github.com/JordanSamhi/Tools/files/12396830/com.ncc.fm48_v1.11_111_1452365854.zip)

Thank you !!!
